// Xcode for Qt project.  
// Generated by create_qt_xcode_project.sh, Laohyx.  
  
#include <QApplication>
#include <QLabel>
#include "mainwindows.h"
#include "glmain.h"
  
int main(int argc, char *argv[]){  
    QApplication app(argc, argv);  
    //QLabel *label = new QLabel("Hello Qt!");
    //label->show();
    //GlMainWindow* mn = new GlMainWindow(0);
    //mn->show();
    GlMainWindow m;
    m.show();
    return app.exec();  
}  

